### ISSUE TITLE
1차 스프린트 개선사항

### ISSUE THREAD

**Issue by Ojongseok** [telling-me/tellingme-Android#26]
### 📃 Description
1차 스프린트(UI 컴포넌트 위주)에서 개선/수정이 필요한 내용입니다.

### ✔ Todo
- [ ] Button의 Ripple(Hover)효과가 텍스트에만 적용되도록 바꾸기
- [x] Button 컴포넌트 중 일부 배경 투명하게 변경
- [ ] 하드코딩 문자열 @stringRes 형태로 변경

### 🔴 ETC
개발 기간: ~ 2024.01.07
