### ISSUE TITLE
2차 스프린트 개선사항

### ISSUE THREAD

**Issue by Ojongseok** [telling-me/tellingme-Android#27]
### 📃 Description
2차 스프린트(기록하기 상세화면)에서 개선/수정이 필요한 내용입니다.

### ✔ Todo
- [x] 키보드 올라오는 이벤트에 따른 UI 대응
-> 기록하는 TextField 영역이 키보드 올라올 때 스크롤 여부와 modifier.weight(1f) 때문에 살짝 어색
- [x] Dialog 컴포넌트화
- [ ] BottomSheet 
-> 컴포넌트화: 현재 나와있는 BottomSheet는 한 종류라 UI 더 나오는거 보고 대응(close 스크롤도 막기)
-> BottomSheet 닫힐 때 true/false 말고 HIDDEN으로 닫기
- [ ] 공개 여부를 설정하는 Switch의 size가 조절되지 않는 이슈(Compose 1.0.4부터 Switch의 사이즈 변경 불가능, 스위치 컴포넌트 자체를 커스텀해서 구성해야 함)
-> 일단 modifier.scale()로 비율을 줄이긴 했는데 완벽하지 않고, Switch의 ripple도 제거해야 하는데 방법을 모르겠음..
- [ ] 툴팁 옆에 뾰족 커스텀

### 🔴 ETC
개발 기간: 2024.01.08 ~ 2024.01.21

**Comment by Ojongseok** [comment]
- 툴팁 레퍼런스 
    - https://stackoverflow.com/questions/75568572/how-to-draw-image-at-particular-position-in-jetpack-compose

**Comment by Ojongseok** [comment]
KeyBoard 올라오고 내려갈 떄 레퍼런스
https://stackoverflow.com/questions/68847559/how-can-i-detect-keyboard-opening-and-closing-in-jetpack-compose
