### ISSUE TITLE
3차 스프린트 개선사항

### ISSUE THREAD

**Issue by Ojongseok** [telling-me/tellingme-Android#31]
### 📃 Description
3차 스프린트(카카오 소셜 로그인)의 진행상황과 앞으로 개선/수정이 필요한 내용입니다.

### ✔ Todo
- [x] 팀블로그 포스팅 작성
- [x] Firebase App Distribution 설정
- [x] http / https 통신 이슈.. 
-> SSL 인증서로 해결
- [x] 카카오로그인 클라&서버쪽 API 연결해서 응답 확인하기
-> 문서가 까다롭기는 한데 적용 완료..
- [x] Retrofit에 CallAdapter 적용하기(ApiResult)
- [x] DataStore로 로컬에서 데이터 관리할 수 있도록 모듈 생성 및 hilt 주입
- [x] State와 Effect로 UI의 모든 상태와 이벤트를 예측가능하도록 설계하는 MVI 패턴 공부, 적용
- [ ] Retrofit 인터셉터로 accessToken/refreshToken 체이닝

### 🔴 ETC
개발 기간: 2024.01.22 ~ 2024.02.07

**Comment by Brightbong92** [comment]
@Ojongseok 님
궁금한점이 있어서 문의드립니다.
초기 폴더 아키텍처 구성하실때 TellingmeApplication을 util 폴더에 넣으신 의도가 궁금합니다.

```xml
...
// AndroidManifest.xml
   android:name=".util.TellingmeApplication"
...
```

**Comment by Ojongseok** [comment]
@Brightbong92 
Application 클래스는 di를 위해서 프로젝트 전역에서 사용되는 클래스라 data, domain, presentaion 레이어와 독립되어 존재하도록 최상위 패키지에 담아뒀습니다! 
최상위에 있는게 맞기는 한데 딱히 담아둘 패키지가 없어서 일단 util에 담아뒀어요ㅎ
