### ISSUE TITLE
4차 스프린트 개선사항

### ISSUE THREAD

**Issue by Ojongseok** [telling-me/tellingme-Android#47]
### 📃 Description
4차 스프린트(Navigation, 로그인 로직)의 진행상황과 앞으로 개선/수정이 필요한 내용입니다.

### ✔ Todo
- [x] 기존 Navigation 구성 -> GraphBuilder 패턴으로 리팩토링
-> 화면 전환할 때 살짝 버벅거리는 이슈...
- [ ] 소셜로그인 / 자동로그인 관련 로직 개선 및 안정화
- [x] 신규 컴포넌트 정의(CheckBox, SelectBox)
- [x] 회원가입 - 닉네임, 생년월일, 직업, 고민 선택 화면 구성
-> 회원가입 Step 화면 리컴포지션 최적화.. LazyColumn에서도 Key로 최적화..

### 🔴 ETC
개발 기간: 2024.02.08 ~ 2023.03.04
